# Generated by Django 4.1.2 on 2022-11-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.TextField(max_length=1000, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from title.', max_length=255, unique=True)),
                ('date_released', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('artiste_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='musicapp.artiste', verbose_name='Artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
                ('song_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='musicapp.song', verbose_name='Song')),
            ],
        ),
    ]
