# Generated by Django 4.1.2 on 2022-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artiste_last_name_alter_lyrics_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
