# Generated by Django 4.1.2 on 2022-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from title.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
    ]
